import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Montserrat } from "@next/font/google";
import { Caveat, Roboto, Dancing_Script, Satisfy } from "next/font/google";
import HeaderC from "@/components/HeaderC";

const caveat = Caveat({
  subsets: ["latin"], // Choose appropriate subsets
  weight: ["400", "700"], // Add font weights as needed
});

// import { Dancing_Script } from '@next/font/google';

// Import the font with your desired weights and subsets
const dancingScript = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust weights as needed
  variable: "--font-dancing-script", // Custom CSS variable for the font
});

const satisfy = Satisfy({
  subsets: ["latin"], // Add subsets based on your use case
  weight: ["400"], // Adjust weights as needed
  variable: "--font-satisfy", // Custom CSS variable
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

// const montserrat = Montserrat({
//   subsets: ['latin'],
//   weight: ['400', '500', '700'], // Specify weights as needed
// });

export const metadata = {
  title: "Hacienda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased bg-gradient-to-tr from-[yellow] to-[black]`}
      > */}
      <body
        className={`${geistSans.variable} ${roboto.className}  antialiased `}
      >
        {/* <Header /> */}
        <HeaderC />
        {children}
        <Footer />
      </body>
    </html>
  );
}
